project:
  type: website
  output-dir: docs
  
website:
  title: "Magic Hands Massage"
  favicon: magic-hands.png
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: solar
    css: styles.css
    toc: true
